version: "3.5"
services:

  api:
    image: node:9.6.1
    command: npm start
    working_dir: /usr/chatty-api
    volumes:
      - .:/usr/chatty-api
    environment:
      DB_PORT: tcp://chatty-db:5432
      DB_USER: user
      DB_PASSWORD: password
      DB_DATABASE: chatty
    depends_on:
      - postgres

  postgres:
    image: postgres:10.2
    command: postgres
      -D /run/postgres-data
      --fsync=off
      --shared-buffers=128kB
      --temp-buffers=800kB
      --work-mem=64kB
      --maintenance-work-mem=1024kB
      --wal-buffers=32kB
      --seq-page-cost=0.01
      --random-page-cost=0.01
      --effective-cache-size=64kB
    container_name: chatty-db
    ports:
      - 5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatty
      PGDATA: /run/postgres-data
